stages:
  - install
  - build
  - test

default:
  image: node:18

cache:
  paths:
    - frontend/node_modules/
    - back/node_modules/

install_dependencies:
  stage: install
  script:
    - echo "Installing backend dependencies..."
    - cd back
    - npm install
    - cd ../frontend
    - echo "Installing frontend dependencies..."
    - npm install

build_frontend:
  stage: build
  script:
    - cd frontend
    - echo "DISABLE_ESLINT_PLUGIN=true" > .env
    - npx update-browserslist-db@latest || true
    - CI=false npm run build

test_backend:
  stage: test
  script:
    - cd back
    - npm test || echo "No backend tests defined"
